logo: images/logo.svg
description: Open source confidence
author: sysagnostic
custom_css:
  - css/custom.css
google_analytics_id: G-N6ZDBM8K2Z
post_share: false
plugins:
  css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/themify-icons/themify-icons.css
    - link: plugins/magnific-popup/magnific-popup.css
    - link: plugins/slick/slick.css
    - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
  js:
    - link: plugins/jquery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/shuffle/shuffle.min.js
    - link: plugins/magnific-popup/jquery.magnific-popup.min.js
    - link: plugins/lazy-load/lozad.min.js
    - link: plugins/google-map/map.js
preloader:
  enable: false
cookies:
  enable: false
map:
  enable: false
social:
  - icon: ti-facebook
    link: https://www.facebook.com/sysagnostic/
  - icon: ti-youtube
    link: https://www.youtube.com/@sysagnostic
  - icon: ti-linkedin
    link: https://www.linkedin.com/company/sysagnostic/
