baseURL = "https://sysagnostic.com"
languageCode = 'en-us'
description = 'sysagnostic website'
theme = "hugo-theme-shell"

[Params]
  [Params.Terminal]
  userName = "root"
  pcName = "sysagnostic"
  workDir = "build"
  profile = "README.md"
  description = "/description.md"
  ps1Delay = 0
  stdoutDelay = 0
  commandDelay = 40
  titleDelay = 0
  contentDelay = 0

  [Params.Tree]
  folderName = "activities"
  files = [ 
    ["blog", "/blog"],
    ["resume", "/resume"],
    ["services", "/services"],
  ]
