name: AWS S3

on:
  push:
    branches:
      - develop
      - www1
      - www2
      - www3

jobs:
  deploy:
    runs-on: ubuntu-22.04
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Upload Website
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'www3.sysagnostic.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'public'

      - name: CDN invalidate
        uses: Comori/aws-s3@v0.1.3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
          invalidation-path: |
            /*
          distribution-id: 'E3NVPIN9JE0SEG'
